defaults:
  - _self_
  - datasets: litbank
  - model: model
  - optimizer: adam
  - trainer: train
  - infra: local

  - experiment: null


metrics: ['MUC', 'Bcub', 'CEAFE']
keep_singletons: True
seed: 0
train: True
eval_all: False

paths:
  resource_dir: ${infra.work_dir}/../coref_resources
  base_data_dir: ${paths.resource_dir}/data
  conll_scorer: ${paths.resource_dir}/reference-coreference-scorers/scorer.pl
  base_model_dir: ${infra.work_dir}/models
  model_dir: null
  best_model_dir: null
  model_filename: 'model.pth'
  model_name: null
  model_name_prefix: 'coref_'
  model_path: null
  best_model_path: null

