defaults:
  - dataset:
    - ontonotes
    - litbank
  - model: model
  - optimizer: adam
  - trainer: train
  - infra: local
  - _self_


metrics: ['MUC', 'Bcub', 'CEAFE']
keep_singletons: True
seed: 0
train: True
eval_all: False

paths:
  resource_dir: ${infra.work_dir}/../coref_resources
  base_data_dir: ${paths.resource_dir}/data
  data_dir: ${paths.base_data_dir}/${dataset.name}/${model.doc_encoder.transformer.name}
  conll_scorer: ${paths.resource_dir}/reference-coreference-scorers/scorer.pl
  base_model_dir: ${infra.work_dir}/models
  model_dir: null
  best_model_dir: null
  model_file: 'model.pth'
  model_name: null

